@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name register_user
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "Tiago Martins",
  "email": "tiago@tiagoweb.com",
  "phone": "51 999999999",
  "password": "123456",
  "confirm_password": "123456"
}

###
# @name updated_user
PUT {{baseUrl}}/user
Content-Type: application/json

{
  "id": "b3f39c74-c6a3-4224-80e2-d2ef397aac5b",
  "name": "James Martins",
  "email": "james@tiagoweb.com",
  "phone": "51 77777777"
}

###
# @name updated_user_with_credentials
PUT {{baseUrl}}/user
Content-Type: application/json

{
  "id": "b3f39c74-c6a3-4224-80e2-d2ef397aac5b",
  "name": "James Martins",
  "email": "james@tiagoweb.com",
  "phone": "51 77777777",
  "password": "teste123",
  "confirm_password": "teste123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "tiago@tiagoweb.com",
  "password": "123456"
}

###

# @name list_categories
GET {{baseUrl}}/categories
Content-Type: application/json
###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 2",
  "content": "Teste"
}

